[project]
name="dlg_heatmap"
version = "0.0.1"
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["heatmap"]
[tool.setuptools.package-data]
"heatmap.data" = ["*.csv"]